import { z } from "zod";

// Core Metrics
export const MetricsSchema = z.object({
  socialImpact: z.number().min(0).max(100),
  financialSustainability: z.number().min(0).max(100),
  riskExposure: z.number().min(0).max(100),
  stakeholderTrust: z.number().min(0).max(100),
});

// A single map node to be rendered by PixiJS
export const MapNodeSchema = z.object({
  id: z.string(),
  x: z.number(), // Isometric grid X
  y: z.number(), // Isometric grid Y
  type: z.enum(["HQ", "COMMUNITY_CENTER", "RESEARCH_LAB", "MARKETING_BILLBOARD", "PRODUCTION_FACILITY", "EMPTY"]),
  status: z.enum(["ACTIVE", "INACTIVE", "DAMAGED", "UPGRADING"]),
});

export const SimulationContextSchema = z.object({
  domain: z.string(),
  purpose: z.string(),
  experienceLevel: z.enum(["BEGINNER", "INTERMEDIATE", "EXPERT"]),
});

export const SimulationStateSchema = z.object({
  budget: z.number(),
  metrics: MetricsSchema,
  turn: z.number(),
  context: SimulationContextSchema.nullable(),
  mapNodes: z.array(MapNodeSchema),
  avatarPos: z.object({ x: z.number(), y: z.number() }),
  lastTransaction: z.object({ cost: z.number(), revenue: z.number(), net: z.number() }).optional(),
  narrativeHistory: z.array(z.string()),
  decisionHistory: z.array(z.object({ title: z.string(), turn: z.number() })),
});

// AI Response validation (F1-F3 Loop)
export const AIConsequenceResponseSchema = z.object({
  narrative: z.string().describe("Narrative explaining the consequence of the user's action"),
  shortTitle: z.string().describe("A 2-4 word title for the decision (e.g. 'Lab Built')"),
  budgetCost: z.number().describe("Budget deducted for the action"),
  revenue: z.number().describe("Revenue generated by the action"),
  metricShifts: z.object({
    socialImpact: z.number(),
    financialSustainability: z.number(),
    riskExposure: z.number(),
    stakeholderTrust: z.number(),
  }).describe("-100 to +100 shift per metric"),
  newNodes: z.array(MapNodeSchema).optional().describe("Any new structures added to the map"),
  updatedNodes: z.array(MapNodeSchema).optional().describe("Any existing map node state changes"),
  avatarPos: z.object({ x: z.number(), y: z.number() }).optional().describe("Manually reposition the character"),
  isGameEnding: z.boolean().describe("Whether this consequence triggered a game over or win condition"),
});
